# Generated by Django 3.0.6 on 2020-06-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0003_userdatabase_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='google_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='linkdin_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
